config/routes.rb
Rails.application.routes.draw do
  
  devise_for :submitters
  devise_for :users
  
  resources :users, only: [:show]
  
  root "posts#index"
  
  resources :posts do
    resources :comments
    member do
    put "likes", to:"posts#upvote"
    put "dislikes", to:"posts#downvote"
    end
  end  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    has_many :comments
    
    acts_as_votable
    
     has_attached_file :image
     validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png",
     "image/gif", "application/pdf"]
    
    def self.search(search)
        if search
            where(["title LIKE ?","%#{search}%"])
        else
            all.order("CREATED_AT DESC")
        end 
    end   
end

app/models/submitter.rb
class Submitter < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :posts  
  has_many :comments
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" } 
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name,:image])
  end  
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    before_action :authenticate_user!
    
    def create
        @post = Post.find(params[:post_id])
        @comment = Comment.create(params[:comment].permit(:content))
        @comment.user_id = current_user.id
        @comment.post_id = @post.id
        
        if @comment.save
            redirect_to post_path(@post)
        else
            render 'new'
        end    
    end
    
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    before_action :set_post , only: [:edit,:update,:show,:destroy,:upvote ,:downvote]
    before_action :authenticate , except: [:index,:show]
    
    def index
        @posts = Post.search(params[:search])  
    end
    
    def show
        @comments = Comment.where(post_id: @post)
        @random_post = Post.where.not(id: @post).order("RANDOM()").first
        
        @post_count = Post.all.count
    end    
    
    def new
        @post = current_user.posts.build
    end
    
    def create
        @post = current_user.posts.build(post_params)
        
        if @post.save
            redirect_to root_path
        else 
            render "new"
        end    
    end
    
    def edit
        
        
    end
    
    def update
        if @post.update(post_params)
            redirect_to @post
        else
            render "edit"
        end    
    end
    
    def destroy
        @post.destroy
        redirect_to root_path
    end
    
    def upvote
        @post.upvote_by current_user
        redirect_to :back
    end 
    
    def downvote
        @post.downvote_by current_user
        redirect_to :back
    end 
    
    private
    
    def authenticate
       authenticate_user! && current_user.admin? 
    end    
    
    def post_params
       params.require(:post).permit(:title,:link,:description ,:image) 
    end 
    
    def set_post
       @post = Post.find(params[:id]) 
    end    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
       @user = User.find(params[:id]) 
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for([@post , @post.comments.build]) do |f| %>
    <%= f.label :content %>
    <%= f.text_area :content %>
    
    <%= f.button :submit , class:"button" %>
<% end %>    
    
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Muse</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css" rel="stylesheet"></link>
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet"></link>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      
      <%= link_to "Dribble" , root_path , class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home" , root_path %></li>
        <li><%= link_to "Create New Dribble" , new_post_path %></li>
        
      </ul>
      
     

      <%= form_tag(posts_path, method: 'get', class: "navbar-form navbar-left") do %>
          <%= text_field_tag :search, params[:search], class: "form-control" , placeholder: "Search Posts"  %>
          <%= submit_tag "Search" , class: "btn btn-default" %>
      <% end %>

      
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li>
                <%= link_to current_user.name, user_path(current_user) %>
            </li>
            <li><%= link_to edit_user_registration_path do  %>
                <i class="glyphicon glyphicon-user"></i> Account Settings
                <% end %>
            </li>
            <li><%= link_to destroy_user_session_path , method: :delete , data: {confirm: "Wanna Log out ?"} do  %>
                <i class="glyphicon glyphicon-log-out"></i> Sign Out
                <% end %>
            </li>
            
            
        <% else %>
            <li><%= link_to new_user_registration_path do  %>
                <i class="glyphicon glyphicon-user"></i> Sign Up
                <% end %>
            </li>
            <li><%= link_to user_session_path do %>
                <i class="glyphicon glyphicon-log-in"> LogIn</i>
                <% end %>
            </li>
        
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div>
  <% flash.each do |name,msg| %>
    <%= content_tag :div , msg , class: "alert alert-info" %>
  <% end %>  
</div>  

<div class="wrapper">
  <%= yield %>
</div>


</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :link %>
      <%= f.text_field :link %>
    </div>
    <div>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <div>
      <%= f.label :Image %>
      <%= f.file_field :image , multiple: true%>
    </div>
    <div>
        
        <%= f.submit %>
    </div>
<% end %>    
    
    

app/views/posts/edit.html.erb
<h1>Edit Form</h1>

<%= render "form" %>

<%= link_to "Back" , post_path %>

app/views/posts/index.html.erb
<div id="intro">
    <% if user_signed_in? %>
        <h3>Hello <%= current_user.name  %> :) </h3>
        <br/>
        <span>
        What Inspires You ? See what inspires others !
        </span>
    <% else %>
        <span>
            What Inspires You ? See what inspires others !
        </span>
    <% end %>  
</div>
  
<div id="posts">
   <% @posts.each do |post| %>
   <div class="post">
      <div class="post_image">
          <%= link_to (image_tag post.image.url(:small)) , post %>
      </div>
      <div class="post_content">
        <div class="title">
            <h2><%= link_to post.title , post %></h2>
        </div>
        <div class="data clearfix">
            <p class="username">Shared By <%= post.user.name %></p>
            <p class="buttons">
                <span>
                    <i class="fa fa-comments-o"></i>
                     <%= post.comments.count %>
                </span>
                <span>
                    <i class="fa fa-thumbs-o-up"></i>
                    <%= post.get_upvotes.size %>
                    
                </span>
                <span>
                    <i class="fa fa-thumbs-o-down"></i>
                    <%= post.get_downvotes.size %>
                    
                </span>
              </p>
        </div>
      </div>
   </div>
     <% end %> 
</div>    

app/views/posts/new.html.erb
<h1>Create a new Post</h1>

<%= render "form" %>

<%= link_to "Home" ,  root_path %>

app/views/posts/show.html.erb
<div id="post_show">
  
  
   <%= link_to  @post.image_file_name,@post.image.url %>
  <h1>
    <%= @post.title %>
  </h1>
  <p class="username">
    Shared by
    <%= @post.user.name %>
    about
    <%= time_ago_in_words(@post.created_at) %>
  </p>
  <div class="clearfix">
    <div class="post_image_description">
      <%= image_tag @post.image.url(:medium) %>
      <div class="description">
        <%= simple_format(@post.description) %>
      </div>
    </div>
    <div class="post_data">
      <%= link_to "Visit Link", "http://#{@post.link}" , class: "button" , target: :_blank %>
      <%= link_to likes_post_path(@post), method: :put, class: "data" do %>
        <i class="fa fa-thumbs-o-up"></i>
        <%= pluralize(@post.get_upvotes.size, "Like") %>
      <% end %>
      <%= link_to dislikes_post_path(@post), method: :put, class: "data" do %>
        <i class="fa fa-thumbs-o-down"></i>
        <%= pluralize(@post.get_downvotes.size, "Dislike") %>
      <% end %>
      <p class="data">
        <i class="fa fa-comments-o"></i>
        <%= pluralize(@post.comments.count, "Comment") %>
      </p>
      <% if @post.user == current_user || current_user.try(:admin?) %>
        <%= link_to "Edit", edit_post_path(@post), class: "data" %>
        <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "data" %>
      <% end %>
    </div>
    <% if @post_count > 2 %>
    <div id="random_post">
      <h3>Random Inspiration</h3>
      <div class="post">
        <div class="post_image">
          <%= link_to (image_tag @random_post.image.url(:medium)), post_path(@random_post) %>
        </div>
        <div class="post_content">
          <div class="title">
            <h2>
              <%= link_to @random_post.title, post_path(@random_post) %>
            </h2>
          </div>
          <div class="data clearfix">
            <p class="username">
              Shared by
              <%= @random_post.user.name %>
            </p>
            <p class="buttons">
              <span>
                <i class="fa fa-comments-o"></i>
                <%= @random_post.comments.count %>
              </span>
              <span>
                <i class="fa fa-thumbs-o-up"></i>
                <%= @random_post.get_likes.size %>
              </span>
            </p>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<div id="comments">
  <h2 class="comment_count">
    <%= pluralize(@post.comments.count, "Comment") %>
  </h2>
  <% @comments.each do |comment| %>
    <div class="comment">
      <p class="username">
        <%= comment.user.name %>
      </p>
      <p class="content">
        <%= comment.content %>
      </p>
    </div>
  <% end %>
  <%= render "comments/form" %>
</div>

app/views/users/show.html.erb
<h1>User Profile Page</h1>

<%= @user.email %>
<%= image_tag @user.image.url(:medium) %>

<h2>Works of <%= @user.name %> :</h2>

<% @user.posts.each do |post|  %>
    <%= link_to post.title , post_path(post) %>
<% end %>    